version: "3"

services:
  mongo_db:
    restart: always
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: node_app
    restart: always
    command: npm run devStart
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app
    links:
      - mongo_db
